export const cars = [
  {
    id: "1",
    brand: "Tesla",
    name: "Model S",
    price: 80000,
    fuel: "Electric",
    seats: 5,
    image: "/car-images/tesla.jpg",
  },
  {
    id: "2",
    brand: "Toyota",
    name: "Camry",
    price: 30000,
    fuel: "Petrol",
    seats: 5,
    image: "/car-images/camry.jpg",
  },
  {
    id: "3",
    brand: "BMW",
    name: "X5",
    price: 50000,
    fuel: "Diesel",
    seats: 5,
    image: "/car-images/bmw.jpg",
  },
  {
    id: "4",
    brand: "Hyundai",
    name: "Creta",
    price: 25000,
    fuel: "Petrol",
    seats: 5,
    image: "/car-images/creta.jpg",
  },
  {
    id: "5",
    brand: "Ford",
    name: "Mustang",
    price: 55000,
    fuel: "Petrol",
    seats: 4,
    image: "/car-images/mustang.jpg",
  },
  {
    id: "6",
    brand: "Audi",
    name: "Q7",
    price: 70000,
    fuel: "Diesel",
    seats: 7,
    image: "/car-images/audi.jpg",
  },
  {
    id: "7",
    brand: "Honda",
    name: "Civic",
    price: 22000,
    fuel: "Petrol",
    seats: 5,
    image: "/car-images/civic.jpg",
  },
  {
    id: "8",
    brand: "Kia",
    name: "Seltos",
    price: 21000,
    fuel: "Petrol",
    seats: 5,
    image: "/car-images/seltos.jpg",
  },
  {
    id: "9",
    brand: "Mercedes",
    name: "GLA",
    price: 65000,
    fuel: "Diesel",
    seats: 5,
    image: "/car-images/mercedes.jpg",
  },
  {
    id: "10",
    brand: "Nissan",
    name: "Leaf",
    price: 29000,
    fuel: "Electric",
    seats: 5,
    image: "/car-images/leaf.jpg",
  },
];
